### ISSUE TITLE
Going the other way

### ISSUE THREAD

**Issue by mcfoton** [mind1master/vk-to-spotify#3]
Yo!
I'm looking for a solution that'll get my starred playlist from Spotify and will add all that tracks to my VK audios. Do you think it's possible in general?

**Comment by mind1master** [comment]
Hi,
I think this is possible. Have a look at `https://pyspotify.mopidy.com/en/latest/api/playlist/#spotify.Playlist.tracks` and `https://vk.com/dev/audio.search`

**Comment by mcfoton** [comment]
Thank you, will look into those 👍
